### ISSUE TITLE
Add proguard rules

### ISSUE THREAD

**Issue by zt64** [kiwicom/navigation-compose-typed#19]
I've added the rules from the README.md for kotlinx-serialization into my proguard file, however I'm still running into issues specifically with this library. 
Calling createRoutePattern results in it throwing an error that the serializer is not found. My code works just fine in debug builds. Is there some rules that need to be added to fix this?

**Comment by hrach** [comment]
We've it deployed (with default rules) in https://github.com/kiwicom/orbit-compose catalog with no issues so far. The same in our production app, though that one without some R8 strict rules. So what is your exception right now?

**Comment by zt64** [comment]
The exception it's throwing doesn't tell much since the classes are obfuscated, but I assume it's referring to my destination class: ```
pu3: Serializer for class 'du' is not found.
Mark the class as @Serializable or provide the serializer explicitly.``` 

These are the destinations I'm using:
```kt
@Serializable
sealed interface RootDestination : Destination {
    val icon: ImageVector

    @get:StringRes
    val label: Int

    companion object {
        val values = mapOf(
            Home to createRoutePattern<Home>(),
            Feed to createRoutePattern<Feed>(),
            Library to createRoutePattern<Library>()
        )
    }

    @Serializable
    object Home : RootDestination {
        override val icon = Icons.Default.Home
        override val label = R.string.home
    }

    @Serializable
    object Feed : RootDestination {
        override val icon = Icons.Default.Subscriptions
        override val label = R.string.feed
    }

    @Serializable
    object Library : RootDestination {
        override val icon = Icons.Default.VideoLibrary
        override val label = R.string.library
    }
}
```

**Comment by hrach** [comment]
Rules are now bundled by default. https://github.com/Kotlin/kotlinx.serialization#android 
Closing here.
