### ISSUE TITLE
DialogResultEffect is called after navigateUp is called

### ISSUE THREAD

**Issue by strajky5** [kiwicom/navigation-compose-typed#33]
Hello, I am using `DialogResultEffect` for getting dialog screen. But on the screen where is it implemented it get dialog result after user click on back button aka `navController.navigateUp()` is called. 

`DialogResultEffect(
		currentRoutePattern = createRoutePattern<ProfileDestinations.Profile>(),
		navController = navController,
	) { result: ProfileDestinations.Logout.Result ->
Timber.d("result: %s", result.requestLogout) // here I received true if navigateUp is called
}`

NavHost looks like:
-> nav graph -> HomeScreen -> nav graph -> Profile screen

- Lib version 0.5.0
- Compose version 1.4.0-alpha05
- Compose nav version 2.5.3
- Android 13 - Google Pixel 6a
- Android 12 - Samsung A51

**Comment by hrach** [comment]
If navigate back/up in demo app in the repository, no result is tracked. Are you sure you don't setup the result? Ideally please send some reproduction or PR to the demo app to showcase the bad behavior.

**Comment by strajky5** [comment]
Ye you are right. I just found out what is problem. It is not called inside the block but somehow if I put there `viewModel` param which is injected by koin it will crash after I go back.

This example will crash but after the app will navigates to prev screen. `doSomething()` is empty method.
Error that I received
`java.lang.IllegalArgumentException: No destination with route xxxx.navigation.ProfileDestinations.Profile is on the NavController's back stack. The current destination is Destination(0xbe180219) route=xxx.navigation.HomeDestinations.Home`
```
fun ProfileScreen(
	navController: NavController,
	viewModel: ProfileViewModel = koinViewModel()
) {
	DialogResultEffect(
		currentRoutePattern = createRoutePattern<ProfileDestinations.Profile>(),
		navController = navController,
	) { result: ProfileDestinations.Logout.Result ->
		viewModel.doSomething()
	}
```

But if I change it to this example then it works
```
fun ProfileScreen(
	navController: NavController,
	viewModel: ProfileViewModel = koinViewModel()
) {
	DialogResultEffect(
		currentRoutePattern = createRoutePattern<ProfileDestinations.Profile>(),
		navController = navController,
	) { result: ProfileDestinations.Logout.Result ->
		Timber.d("hello")
	}
```

**Comment by hrach** [comment]
Could you please provide some small reproducible build - either zip or PR? Thx!

**Comment by hrach** [comment]
I have a reproduction. Investigating now.
