### ISSUE TITLE
Add an option to `popUpTo` a specific destination

### ISSUE THREAD

**Issue by StylianosGakis** [kiwicom/navigation-compose-typed#41]
Do you think this function

```kotlin
@ExperimentalSerializationApi
@MainThread
fun NavOptionsBuilder.popUpTo(
  route: Destination,
  popUpToBuilder: PopUpToBuilder.() -> Unit = {},
) {
  popUpTo(route.toRoute(), popUpToBuilder)
}
```

Would make sense? I wanted to at some point to navigate but also pop up to a destination in the meantime, with code like this:
```kotlin
composable<Destinations.TerminationDate>() { navBackStackEntry ->
  val viewModel // ...
  TerminationDateDestination(
    ..
    navigateToSuccessScreen = {
      navController.navigate(
        CancelInsuranceDestinations.TerminationSuccess,
        navOptions {
          popUpTo(Destinations.CancelInsurance)
        },
      )
    },
  )
}
```

and `toRoute()` is internal so I couldn't do `popUpTo(Destinations.CancelInsurance.toRoute())` really.
For now I got this one file where I've set `@file:Suppress("INVISIBLE_MEMBER", "INVISIBLE_REFERENCE")` to abuse all these internal functions so here I am asking for your thoughts about exposing some of them 😅

It seems to work for me, am I possibly missing something that wouldn't make this a good idea? What do you think?

**Comment by StylianosGakis** [comment]
Hmm yeah, if the destination itself isn't an object but it's a data class, it'd require us to construct an object of it to pass it as `Destination`.
Maybe there's some room to pass a `KClass<Destination>` or a Serializer of that class or something like that, but that requires using even more of the internal functions of this library, might try that out at some point in the future though 🤔

**Comment by hrach** [comment]
> Hmm yeah, if the destination itself isn't an object but it's a data class, it'd require us to construct an object of it to pass it as Destination.

Yes, + previously it was not possible to pass there an URL with prefilled values. This is getting supported in Navigation 2.6.

Anyway, we have solution that could work for you now:

```kotlin
navController.navigate(CancelInsuranceDestinations.TerminationSuccess) {
  popUpTo<Destinations.CancelInsurance>()
}
```

**Comment by StylianosGakis** [comment]
It already exists, you're way ahead of me 😅
Thanks a lot, this works, I just missed this API

**Comment by Twinsen81** [comment]
> Anyway, we have solution that could work for you now:
> navController.navigate(CancelInsuranceDestinations.TerminationSuccess) {
>   popUpTo<Destinations.CancelInsurance>()
> }

But what if the `Destination` to pop back to comes as a parameter:
```
@Composable
fun NavigationEffects(
    intent: NavigationIntent,

...

    when (intent) {
        is NavigationIntent.NavigateBack -> {
            if (intent.backDestination != null) {
                navController.popBackStack(
                    route = intent.backDestination.toRoute()
                )
                    
```
In that case I need access to `toRoute()`. Or there's another workaround?

**Comment by hrach** [comment]
The specific route (uri) is supported directly by Navigation Compose. Alternatively, you may transfer a route patter in the parameter and pass that.
