### ISSUE TITLE
Consider using the stable compose BOM instead of the alpha one from Chris Banes

### ISSUE THREAD

**Issue by StylianosGakis** [kiwicom/navigation-compose-typed#58]
I noticed that in the latest update of the library there was a bump in the compose BOM and that's when I noticed that the alpha compose bom is used https://github.com/kiwicom/navigation-compose-typed/blob/61a53d63a50364fe37014dec4da5bdd0df6f7d1e/gradle/libs.versions.toml#L12

Is there some particular reason why that is the case? It'd be nice not to bring in the alpha dependencies by accident by using this library. I haven't encountered any specific problem in my case, but it makes me a bit reluctant to know that I'll always be bringing in all the alphas without realizing. What is your opinion about this?

**Comment by hrach** [comment]
It should not bring any alpha dependency to the project, as we depend only on stable navigation compose, which is not part of the bom. The lib also uses compose compiler, which is versioned explicitly. This is for demo, but I'll fix it anyway, thanks.

**Comment by StylianosGakis** [comment]
Ah I should've looked into where it's actually used to figure that this is the case. Sorry about that, and thanks for the reply! 🙏
