### ISSUE TITLE
Posibility to add more serializable types to the `SerializersModule` that this library is using, which aren't necessary of the `Destination` type.

### ISSUE THREAD

**Issue by StylianosGakis** [kiwicom/navigation-compose-typed#70]
So I have this use case where I'd like to have my destinations to take in a list with type `ImmutableList` from kotlinx.collections.immutable.ImmutableList.

In order for this to work, it needs to know how to serialize this type, but I don't see an entry point from this library to add it to the SerializersModule that it's using. 

Am I missing something perhaps? What would you suggest to do instead if this isn't something that could really work with how everything is setup?

**Comment by StylianosGakis** [comment]
Seems like this isn't something that can be fixed in this level in the first place.
Even if I have access to the SerializersModule and the builder, there doesn't seem to exist a way to make it be able to figure out how to serialize ImmutableList.

What I've done instead was that in the models themselves that are used in those destinations, I have added `@Serializable(ImmutableListSerializer::class)` where `ImmutableListSerializer` is
```kotlin
@Serializer(forClass = ImmutableList::class)
class ImmutableListSerializer<T>(private val dataSerializer: KSerializer<T>) : KSerializer<ImmutableList<T>> {
  private class PersistentListDescriptor : SerialDescriptor by serialDescriptor<List<String>>() {
    override val serialName: String = "kotlinx.serialization.immutable.ImmutableList"
  }

  override val descriptor: SerialDescriptor = PersistentListDescriptor()
  override fun serialize(encoder: Encoder, value: ImmutableList<T>) {
    return ListSerializer(dataSerializer).serialize(encoder, value.toList())
  }

  override fun deserialize(decoder: Decoder): ImmutableList<T> {
    return ListSerializer(dataSerializer).deserialize(decoder).toPersistentList()
  }
}
```

And that seems to work just fine.
A big shame I can't find a way not to have to define this in each property of all possible models that my destinations will use, but this isn't something for this library to solve as I see it. I am either missing something, or I can't do it anyway in the first place.

I think this can be just closed, just leaving it open so you take a look at it too. I wonder if you've though of (or tried to) doing something like this before and what approach you chose instead.

**Comment by StylianosGakis** [comment]
Seems like this isn't something that can be fixed in this level in the first place.
Even if I have access to the SerializersModule and the builder, there doesn't seem to exist a way to make it be able to figure out how to serialize ImmutableList.

What I've done instead was that in the models themselves that are used in those destinations, I have added `@Serializable(ImmutableListSerializer::class)` where `ImmutableListSerializer` is
```kotlin
@Serializer(forClass = ImmutableList::class)
class ImmutableListSerializer<T>(private val dataSerializer: KSerializer<T>) : KSerializer<ImmutableList<T>> {
  private class PersistentListDescriptor : SerialDescriptor by serialDescriptor<List<String>>() {
    override val serialName: String = "kotlinx.serialization.immutable.ImmutableList"
  }

  override val descriptor: SerialDescriptor = PersistentListDescriptor()
  override fun serialize(encoder: Encoder, value: ImmutableList<T>) {
    return ListSerializer(dataSerializer).serialize(encoder, value.toList())
  }

  override fun deserialize(decoder: Decoder): ImmutableList<T> {
    return ListSerializer(dataSerializer).deserialize(decoder).toPersistentList()
  }
}
```

And that seems to work just fine.
A big shame I can't find a way not to have to define this in each property of all possible models that my destinations will use, but this isn't something for this library to solve as I see it. I am either missing something, or I can't do it anyway in the first place.

I think this can be just closed, just leaving it open so you take a look at it too. I wonder if you've though of (or tried to) doing something like this before and what approach you chose instead.

**Comment by hrach** [comment]
There are these alternatives:
- [Specifying serializers for a file](https://github.com/Kotlin/kotlinx.serialization/blob/ba7d17a15329840a85e823c6d4bdc3595d8a19c6/docs/serializers.md#specifying-serializers-for-a-file)
- [Specifying serializer globally using typealias](https://github.com/Kotlin/kotlinx.serialization/blob/ba7d17a15329840a85e823c6d4bdc3595d8a19c6/docs/serializers.md#specifying-serializer-globally-using-typealias)

I guess that's all what can be done here.
