### ISSUE TITLE
Include bottomSheet() in library?

### ISSUE THREAD

**Issue by WildOrangutan** [kiwicom/navigation-compose-typed#97]
Hey, 

I'm wondering... why not also include [bottomSheet()](https://github.com/kiwicom/navigation-compose-typed#extensibility) in the library?

**Comment by hrach** [comment]
The main motivation is that the bottomsheet integration is in accompanist and just for material 2, i.e. it is quite a fragile dependency.

**Comment by hgarciaalberto** [comment]
Any update on this, @hrach ?
